// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxzzqzbbbozpsqxvfjud.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4enpxemJiYm96cHNxeHZmanVkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NDYzMzYsImV4cCI6MjA1MTEyMjMzNn0.36ZQeCbOkOd8RwcPBjKRZZpPU5d5g4MEg3Xh-RrmuU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);